-- Shortener module schema. Portable SQL (H2 + PostgreSQL).
-- Migrations are append-only: never edit an applied file; add V<n+1> instead.

CREATE TABLE short_link (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(30)              NOT NULL,
    original_url      VARCHAR(2048)            NOT NULL,
    custom_alias      BOOLEAN                  NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at        TIMESTAMP WITH TIME ZONE,
    deactivated_at    TIMESTAMP WITH TIME ZONE,
    -- Denormalized counter: O(1) total for analytics, updated atomically per click.
    click_count       BIGINT                   NOT NULL DEFAULT 0,
    last_accessed_at  TIMESTAMP WITH TIME ZONE,
    -- Optimistic locking for state changes (deactivation); click updates bypass it on purpose.
    version           BIGINT                   NOT NULL DEFAULT 0,
    -- Uniqueness is enforced by the database, not by a check-then-insert in code,
    -- so concurrent creations with the same code cannot both succeed.
    CONSTRAINT uk_short_link_code UNIQUE (code)
);

CREATE TABLE click_event (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id            BIGINT                   NOT NULL,
    occurred_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Privacy (NFR-6): no IP address, no full referrer URL, no raw user agent.
    referrer_host      VARCHAR(255),
    user_agent_family  VARCHAR(32)              NOT NULL,
    CONSTRAINT fk_click_event_link FOREIGN KEY (link_id) REFERENCES short_link (id)
);

-- Serves the analytics queries: clicks for one link, bucketed by time.
CREATE INDEX ix_click_event_link_time ON click_event (link_id, occurred_at);
